### ISSUE TITLE
Provide the right set of plugins to make default.scsyndef work!

### ISSUE THREAD

**Issue by glastonbridge** [glastonbridge/SuperCollider-Android#2]
At the moment, I'm seeing a caught exception (hurrah!) that it can't find UGen "Control"

**Comment by danstowell** [comment]
Yep, Control is used for the external controls (aka arguments) such as freq, amp. The default synthdef is defined somewhere inside common/build/SCClassLibrary/Common/Collections/Event.sc and you can see exactly which ugens are used by running this in sc:

```
   s.boot;
   x = Synth(\default)
   x.trace
```

it looks like it uses:
- Control, OffsetOut - from IOUGens.cpp
- LPF - from FilterUGens.cpp
- Rand - from NoiseUGens.cpp
- VarSaw, XLine, Linen - from LFUGens.cpp
- Pan2 - from PanUGens.cpp

**Comment by glastonbridge** [comment]
Added plugins and checked in.
